import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import qm9_configs
import synthetic_config
import zinc_config
import community_small_config
import ego_small_config
import enzymes_config

import default_qm9_sample_config as default_qm9_sample
import default_zinc_sample_config as default_zinc_sample

import default_community_small_config as default_community_small
import default_community_small_sample_config as default_community_small_sample

import default_ego_small_config as default_ego_small
import default_ego_small_sample_config as default_ego_small_sample

import default_enzymes_config as default_enzymes
import default_enzymes_sample_config as default_enzymes_sample

import default_grid_config as default_grid
import default_grid_sample_config as default_grid_sample